### ISSUE TITLE
Update Bundle for Akeneo 2.3

### ISSUE THREAD

**Issue by claudioflagbit** [flagbit/akeneo-table-attribute-bundle#1]
Akeneo 2.3 was released and for being able to use this bundle for the newest version, it needs to be tested and updated in case of breaks.

https://www.akeneo.com/release-notes/

**Comment by amansilla** [comment]
Hi @claudioflagbit! a bit delayed but finally we got today new version 2.1.2 released, tested with Akeneo 2.3 LTS and seems to work properly. So I'll close this issue and assume this is all properly working, otherwise we can reopen this issue again.
