### ISSUE TITLE
Cover Akeneo TableAttributeBundle with tests

### ISSUE THREAD

**Issue by flagbird** [flagbit/akeneo-table-attribute-bundle#2]
Currently there are still tests missing for this bundle for the PHP and Javascript part. 

* Check if the code is testable and create tests
* Look into the need of integration tests with Akeneo, so there can be checks for BC
* Make tests run with all supported Akeneo versions
   * For easier implementation always test with the latest patch version. This can be improved later

**Comment by amansilla** [comment]
Maybe it will be a better idea to create separate issues for every bullet otherwise this issue will be the never ending story.

**Comment by flagbird** [comment]
#18 is already handling those, because the migration (and future migrations) benefits from tests.

**Comment by amansilla** [comment]
Great, so that means this can be closed once #18 is merged.

**Comment by amansilla** [comment]
I'll close this issue since #18 which includes tests got merged.
