### ISSUE TITLE
[BUG] Dropbox rendering wrong when there are a lot of columns

### ISSUE THREAD

**Issue by jkniest** [flagbit/akeneo-table-attribute-bundle#4]
When I create a lot of columns the items in the dropdown field in the first row will not be visible. I've attached a screenshot:

![image](https://user-images.githubusercontent.com/15618191/43770101-aabd3610-9a3b-11e8-9abc-db5f2a8a3cb4.png)

Thanks for any help,
Jordan Kniest

**Comment by amansilla** [comment]
Hi @jkniest! first thank you for reporting the issue. It seems like a bug but could you provide some important information for being able to reproduce it e.g. Akeneo version, CE or EE?

**Comment by jkniest** [comment]
Hey @amansilla,

sure..

We are using the enterprise edition of Akeneo with the version 2.0.32. In the table are 11 columns (it's a mix of select fields and numbers).

Our workflow:
- We created a new attribute of type table
- Added a lot of columns (the first one must be a simple select)
- Attached the attribute to a family
- Created a product with the family

If you need any more information feel free to ask..

Thanks for your help
Jordan Kniest

**Comment by amansilla** [comment]
Hi @jkniest! We've released the `v2.1.4` that fix this problem, so I close this issue.
