### ISSUE TITLE
Composer hangs forver during install. 

### ISSUE THREAD

**Issue by onlyapproved** [flagbit/akeneo-table-attribute-bundle#41]
Hey Guys. 

We are finding on both Staging and Prod, that the installation of the flagbit module hangs when updating dependencies (Including require-dev) 

not really much i can provide from logs at this point, as the server is unreachable, and i dont want to risk data loss. It has been working for the past 15 minutes now at 80% CPU ultilization.

https://prnt.sc/qpj0b4

Will post some more logfiles when i get access to the server again. 

Update 40 minutes post installing the repository. 

Had to force server to stop, and re-launch. 

Status : Server is not reachable, and looks like i need to recover from backup.

**Comment by amansilla** [comment]
For me the issue doesn't seems to be related with this extension but with your project dependencies. If you have any problem during the installation of any package installed by composer you can go rollback the changes by just uninstalling the extension with `composer remove package-name` in this specific case by typing `composer remove flagbit/table-attribute-bundle`.

I'll close this issue, don't hesitate to reopen if the issue persists.
