### ISSUE TITLE
Issue with flagbit bundle

### ISSUE THREAD

**Issue by tintusumith** [flagbit/akeneo-table-attribute-bundle#6]
Hi,
I installed akeneo-table-attribute-bundle in our akeneo application. I completed all steps described in installation steps. But when I creating an table attribute , and click on column tab some errors occured.
Error is:
akeneo-table-attribute-bundle
Attribute type flagbit_catalog_table must be configured to display attribute Specifications as grid column

How can I fix this?

**Comment by amansilla** [comment]
Hi @tintusumith!

Could you please provide some basic information? e.g. Akeneo, Table Attribute Bundle and PHP Versions used.

Some screen capture would be very appreciated as well!

**Comment by tintusumith** [comment]
I used akeneo 2.3 version and  flagbit bundle https://github.com/Flagbit/akeneo-table-attribute-bundle.
![screensho7](https://user-images.githubusercontent.com/35957640/47708665-8d40d500-dc54-11e8-9b48-57da2a3b19b0.png)
![screenshot from 2018-10-30 14-52-27](https://user-images.githubusercontent.com/35957640/47708672-916cf280-dc54-11e8-99c3-9c72b2125b52.png)

**Comment by amansilla** [comment]
Hi @tintusumith! sorry for the delay but today a new version 2.1.2 of the bundle was released, which adds support for Akeneo 2.3 and fix some bugs.

I'll close this issue and assume the new release fix the bug, if the bug in your case still is produced, let me know and will reopen the issue and do further investigations.
