### ISSUE TITLE
Problems with the validation when setting a table attribute (Akeneo 5.0.43)

### ISSUE THREAD

**Issue by tdoedtmann** [flagbit/akeneo-table-attribute-bundle#63]
A `Table` Attribute with columns of type `Text` and `SimpleSelect` was created. No `Validation` is defined for either of them.
Nevertheless, the Attribute cannot be created for a Product without selecting an option from the `SimpleSelect`.

![image](https://user-images.githubusercontent.com/1023513/128374297-3929e8de-f6f6-44c6-a9ac-07a6d7822407.png)

**Comment by flagbird** [comment]
@tdoedtmann Thank you for reporting this issue too.
